import { CORE_SETTINGS } from './core';
import { PLUGINS } from './plugins';
import { coreEnvVar, pluginEnvVar, type SettingDef } from './types';

export type SettingsValues = Record<string, string>;

/** Key used in the values map: core keys plain, plugin keys namespaced. */
export function valueKey(pluginName: string | null, key: string): string {
    return pluginName ? `${pluginName}.${key}` : key;
}

function isDefault(def: SettingDef, raw: string): boolean {
    if (raw === '') return true;
    if (def.default === undefined) return false;
    if (def.kind === 'json') {
        try {
            return JSON.stringify(JSON.parse(raw)) === JSON.stringify(def.default);
        } catch {
            return false;
        }
    }
    return String(def.default) === raw;
}

function envValue(def: SettingDef, raw: string): string {
    const value = raw.trim();
    // Compose env values with spaces/JSON survive fine unquoted in env_file,
    // but quote when they contain whitespace or '#' for .env robustness.
    return /[\s#"']/.test(value) ? JSON.stringify(value) : value;
}

export interface GeneratedEnv {
    envFile: string;
    composeSnippet: string;
    /** Validation problems, e.g. required settings that are missing. */
    problems: string[];
}

/**
 * Renders the .env.riven file and docker-compose `environment:` snippet from
 * the form values. Only non-default values are emitted.
 */
export function generateEnv(values: SettingsValues, enabledPlugins: string[]): GeneratedEnv {
    const lines: string[] = [];
    const problems: string[] = [];

    const emit = (envVar: string, def: SettingDef, raw: string | undefined, required: boolean) => {
        const value = raw?.trim() ?? '';
        if (required && value === '') {
            problems.push(`${envVar} is required`);
        }
        if (value === '' || isDefault(def, value)) return;
        if (def.kind === 'json') {
            try {
                JSON.parse(value);
            } catch {
                problems.push(`${envVar} is not valid JSON`);
                return;
            }
        }
        if (def.kind === 'int' && !/^-?\d+$/.test(value)) {
            problems.push(`${envVar} must be an integer`);
            return;
        }
        if (def.kind === 'bool' && !/^(true|false)$/i.test(value)) {
            problems.push(`${envVar} must be true or false`);
            return;
        }
        lines.push(`# ${def.description.split('\n')[0]}`);
        lines.push(`${envVar}=${envValue(def, value)}`);
    };

    lines.push('# riven-ts configuration — generated by the Riven frontend');
    lines.push('# Apply by mounting as env_file and restarting the riven-ts container.');
    lines.push('');

    for (const def of CORE_SETTINGS) {
        if (def.key === 'enabledPlugins') continue; // handled below
        emit(coreEnvVar(def.key), def, values[valueKey(null, def.key)], Boolean(def.required));
    }

    // enabledPlugins from the plugin toggles
    const enabled = enabledPlugins.filter(
        (name) => !PLUGINS.find((plugin) => plugin.name === name)?.permanent
    );
    if (enabled.length > 0) {
        lines.push('# A list of core plugins to enable.');
        lines.push(`${coreEnvVar('enabledPlugins')}=${JSON.stringify(enabled)}`);
    }

    for (const plugin of PLUGINS) {
        const active = plugin.permanent || enabledPlugins.includes(plugin.name);
        if (!active) continue;
        const pluginLines: string[] = [];
        for (const def of plugin.settings) {
            const raw = values[valueKey(plugin.name, def.key)];
            const before = lines.length;
            emit(
                pluginEnvVar(plugin, def.key),
                def,
                raw,
                Boolean(def.required) && !plugin.permanent
            );
            if (lines.length > before) pluginLines.push(...lines.splice(before));
        }
        if (pluginLines.length > 0) {
            lines.push(`# ── ${plugin.label} ──`);
            lines.push(...pluginLines);
        }
    }

    const envFile = lines.join('\n') + '\n';

    const composeSnippet = [
        '    environment:',
        ...lines.filter((line) => line && !line.startsWith('#')).map((line) => `      - ${line}`)
    ].join('\n');

    return { envFile, composeSnippet, problems };
}

/** Parses an existing .env.riven back into form values (for the import box). */
export function parseEnvFile(content: string): {
    values: SettingsValues;
    enabledPlugins: string[];
} {
    const values: SettingsValues = {};
    let enabledPlugins: string[] = [];

    for (const rawLine of content.split('\n')) {
        const line = rawLine.trim();
        if (!line || line.startsWith('#')) continue;
        const eq = line.indexOf('=');
        if (eq === -1) continue;
        const envVar = line.slice(0, eq).trim();
        let value = line.slice(eq + 1).trim();
        if (
            (value.startsWith('"') && value.endsWith('"')) ||
            (value.startsWith("'") && value.endsWith("'"))
        ) {
            try {
                value = value.startsWith('"') ? (JSON.parse(value) as string) : value.slice(1, -1);
            } catch {
                value = value.slice(1, -1);
            }
        }

        if (envVar === coreEnvVar('enabledPlugins')) {
            try {
                const parsed = JSON.parse(value) as unknown;
                if (Array.isArray(parsed)) enabledPlugins = parsed.map(String);
            } catch {
                // ignore malformed enabledPlugins
            }
            continue;
        }

        if (envVar.startsWith('RIVEN_PLUGIN_SETTING__')) {
            const rest = envVar.slice('RIVEN_PLUGIN_SETTING__'.length);
            const separator = rest.indexOf('__');
            if (separator === -1) continue;
            const prefix = rest.slice(0, separator);
            const key = rest.slice(separator + 2);
            const plugin = PLUGINS.find((candidate) => candidate.envPrefix === prefix);
            if (plugin) values[valueKey(plugin.name, key)] = value;
            continue;
        }

        if (envVar.startsWith('RIVEN_SETTING__')) {
            values[valueKey(null, envVar.slice('RIVEN_SETTING__'.length))] = value;
        }
    }

    return { values, enabledPlugins };
}
